# Generated by Django 6.0.3 on 2026-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery_area',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
